---
author:
  - Raju Rimal
  - Trygve Almøy
  - Solve Sæbø
opening: Dear Professor Xu,
closing: Sincerely,
date: '`r format(Sys.Date(), "%d %B, %Y")`'
return-address:
  - 'Universitetstunet 3'
  - '1430, Ås'
  - '\textsc{norway}'
address:
  - Qing-Song Xu,
  - Editor
  - Chemometrics and Intelligent Laboratory Systems
signature: Signature.png
signature-before: -6ex
signature-after: 0ex
colorlinks: true
fontsize: 11pt
papersize: a4
geometry: "margin=0.9in"
output: linl::linl
---


```{r, include = FALSE}
refs <- bibtex::read.bib("./References.bib", encoding="UTF-8")
```

The focus of this study is an attempt to make a thorough comparison of the estimation performance of different methods with data simulated from a linear model whose latent structures are controlled by a small set of parameters. While finding and interpreting the influences between the variables, estimation plays an important role in all fields and is also desirable in chemometrics. As an extension to the previous article^[`r paste(capture.output(refs[["rimal2019pred"]]), collapse=" ")`], published in the journal of Chemometrics and Intelligent Laboratory Systems, this study explores the interaction between the properties of data and estimations made by various methods.

This comparison is unique in two different aspects: a) the study of correlations in both the response and the predictors on the estimation performance in comparison with prediction performance and b) comparison of new and promising methods based on envelope estimation with more established methods such as PLS and PCR, which are well known in chemometrics. Both of these reasons make, in our opinion, this study highly relevant to chemometrics society. We would also like to inform that this study is not an additional groundbreaking method or result that we have added to society. However, this can be a reference to the people working on the formulation of models and using various methods to leverage latent structures in both predictors and responses. Both of these will be a supplement for researchers who are developing or want to implement and understand the behaviour of new methods in their study.

We would like to appreciate the reviewers' concerns and suggestions which have helped us to improve the quality of this article. This study compares the methods based on their estimation performance that requires the true relationship (regression coefficients). In the case of a real dataset, finding the true relation is not possible. Although we were able to include two examples in the previous study of prediction comparison, we are not able to include an example with real dataset in this study as requested by the first reviewer.

Furthermore, we have made some changes based on the comment of Reviewer-1 and Reviewer-2. A separate PDF file with these changes is attached to this letter. 

Reference: 
: `CHEMOLAB_2019_407`

Title: 
: Comparison of Multi-response Estimation Methods

