# Simulation Model #

As a follow-up, this study will continue using the same simulation model used by @rimal2019pred. The data is simulated from a multivariate normal distribution where we assume that the variation in response variable y is partly explained by the predictor variable $x$. However, in many situations, only a subspace of the predictor space is relevant for the variation in the response $y$. This space can be referred to as the relevant space of $x$ and the rest as irrelevant space. In a similar way, for a certain model, we can assume that a subspace in the response space exists and contains the information that the relevant space in predictor can explain (Figure \@ref(fig:relevant-space)).

```{r relevant-space, out.width = "80%", fig.asp = 0.7, retina = 2, fig.align = 'center', message = FALSE, fig.cap = "Relevant space in a regression model"}
plot_relspace()
```

Following the concept of relevant space, a subset of predictor components can be imagined to span the predictor space. These components can be regarded as relevant predictor components. @Naes1985 introduced the concept of relevant components which was explored further by @helland1990partial, @naes1993relevant, @Helland1994b and @Helland2000. The corresponding eigenvectors were referred to as relevant eigenvectors. A similar logic is introduced by @cook2010envelope and later by @cook2013envelopes as an envelope which is the space spanned by the relevant eigenvectors [@cook2018envelope, , p.101]. See @Rimal2018, @saebo2015simrel  and @rimal2019pred for in-depth background on the model.

