# Discussion and Conclusion

The overall performance of all methods highly depends on the nature of the data. The MANOVA plots show that most of the simulation parameters, except `p`, has significant interaction with the methods. In addition, the high interaction of `gamma` with the `relpos` parameter suggests to carefully consider the number of relevant predictor components in the case of highly multicollinear data since this choice may have a large effect on the results. Although the interaction does not have this extent of influence in prediction, one should be careful about interpreting the estimates. In such cases, careful validation of model complexity, preferably using cross-validation or test data is advisable also for estimation purposes.

Designs with low multicollinearity and independent responses are in favour of envelope methods. The methods have produced the smallest prediction and estimation error with significantly few numbers of components in these designs. However, as the correlation in the responses increases, the estimation error in envelope methods in most cases also increases noticeably. This indicates that the reduction of the response space becomes unstable with high collinearity between the responses for the envelope methods. Despite the interaction of the `eta` parameter with the method is significant, the extent of its effect is rather small compared to both main and interaction effect of `gamma` and `relpos`. 

The effect of the number of variables is negligible in all cases for all designs. Here the use of principal components for reducing the dimension of $n<p$ designs, as in @rimal2019pred, has been useful so that we were able to model the data using envelope methods without losing too-much variation in the data.

Both prediction and estimation corresponding to PCR methods are found to be stable even when the non-optimal number of components are used. The PLS1 method, which models the responses separately, is in general performing poorer than other methods. Unlike in prediction comparison, the performance of the envelope methods is comparable to the others except for the use of the number of components to obtain the minimum estimation error. The envelope methods have used 1-2 components in almost all designs, which is quite impressive. However, non-optimal number of components can lead to large estimation error, so one should be careful in this respect while using the envelope methods. Both PLS1 and PLS2 use a smaller number of components when the relevant components are at positions 1, 2, 3, 4. However, both methods used 7-8 components for the designs with relevant components at positions 5, 6, 7, 8.

We expect the results from this study may help researchers, working on theory, application and modelling, to understand these methods and their performance on data with varying properties.

The first part of this study [@rimal2019pred] on prediction comparison should be considered to obtain a comprehensive view of this comparison. A shiny [@shiny] web application at [http://therimalaya.shinyapps.io/Comparison](http://therimalaya.shinyapps.io/Comparison) allows readers to explore all the visualizations for both prediction and estimation comparisons. In addition, a GitHub repository at [https://github.com/therimalaya/04-estimation-comparison](https://github.com/therimalaya/04-estimation-comparison) can be used to reproduce this study.
